### ISSUE TITLE
Is it possible to use redmine_git_hosting with git/gitolite installed on a different server ?

### ISSUE THREAD

**Issue by VoidAndAny** [jbox-web/redmine_git_hosting#278]
First thanks for your job, previous redmine gitolite I use were not so well done and maintained...

As I write on the subject is it possible to use redmine_git_hosting with git/gitolite installed on a different server ?

Server 1 : redmine + redmine_git_hosting 
Server 2 : git + gitolite

Second question is github issues are the right place to ask question ?
I try to migrate from an old installation of redmine/gitolite to redmine_git_hosting I will probably have a lot of problem (importation of previous git repo, user access and right, gitolite.conf, user public keys...)...

**Comment by sheltonash** [comment]
@n-rodriguez Before I go completely crazy with my understanding.  I get that we cannot have redmine and all our local repositories on the same server (due to your latency concerns previously mentioned) but should I be able to administer a remote gitolite installation (or else why can I specify a hostname and port for the gitolite installation ?)

**Comment by n-rodriguez** [comment]
> I get that we cannot have redmine and all our local repositories on the same server

Weird... actually you can and you must do like this.

> should I be able to administer a remote gitolite installation (or else why can I specify a hostname and port for the gitolite installation ?

With the latest version of Redmine Git Hosting you can but it's not advised. See here : https://github.com/jbox-web/redmine_git_hosting/issues/546
