### ISSUE TITLE
Error in statistics view

### ISSUE THREAD

**Issue by n-rodriguez** [jbox-web/redmine_git_hosting#322]
```
ActionView::Template::Error (PG::GroupingError: ERROR:  column "changesets.id" must appear in 
the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT "changesets".* FROM "changesets"  WHERE "changesets"....
               ^
: SELECT "changesets".* FROM "changesets"  WHERE "changesets"."repository_id" = 1 AND (user_id IS NOT NULL) GROUP BY committer):

...
...
plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/repository_patch.rb:170:in `commits_per_author_with_aliases'
```

**Comment by dgeo** [comment]
Same bug here...

If it can help, this sql query works:
`SELECT "changesets".committer,count(id) FROM "changesets"  WHERE "changesets"."repository_id" = 1 AND (user_id IS NOT NULL) GROUP BY committer`

I may try patches here too :)

**Comment by RomanSyroeshko** [comment]
Hello @n-rodriguez,

We experience the same problem after migration from 0.6.2 onto 0.7.10.

Any changes to get it fixed in 0.7.x branch?

Thanks.

**Comment by n-rodriguez** [comment]
> Any chance to get it fixed in 0.7.x branch?

Nope. I won't do other fixes on the 0.7 branch.

**Comment by niosHD** [comment]
I just upgraded to the recent development version of the plugin and redmine 3.0.0 and want to report another SQL problem which is related to the statistic functionality. It is definitely not the same bug like above which seems to be a postgres vs mysql incompatibility. However, maybe they could be fixed in one go.

The Query from [repository_commits_stats.rb#L133](https://github.com/jbox-web/redmine_git_hosting/blob/devel/app/reports/repository_commits_stats.rb#L133) crashes with the following error:
```
Mysql2::Error: Unknown column 'changes.commit_date' in 'order clause': SELECT COUNT(*) AS count_all, commit_date AS commit_date FROM `changes` INNER JOIN `changesets` ON `changesets`.`id` = `changes`.`changeset_id` WHERE (changesets.repository_id = 11) GROUP BY commit_date  ORDER BY `changes`.`commit_date` ASC
```

I suspect that it is a result of the active record update which came with the new redmine.

**Comment by n-rodriguez** [comment]
@niosHD 
> It is definitely not the same bug like above which seems to be a postgres vs mysql incompatibility.

Thanks for your feedback but can you please open a new issue, I'm gonna close this one :)
