### ISSUE TITLE
Initialization of the repo with README file no longer works, after gitolite.conf is auto-updated by Redmine

### ISSUE THREAD

**Issue by necramirez** [jbox-web/redmine_git_hosting#338]
I followed the instructions here: https://jbox-web.github.io/redmine_git_hosting/configuration/troubleshooting/#initialization-of-the-repo-with-readme-file-does-not-work

However, when I create a new project and repo and Redmine updates gitolite.conf to include that new repo, the config for `repo @all` disappears.

**Comment by n-rodriguez** [comment]
> However, when I create a new project and repo and Redmine updates gitolite.conf to include that new repo, the config for repo @all disappears.

Weird...

**Comment by necramirez** [comment]
Since, to add the `repo @all` config, I have to do it by hand, do you think it's worth making this a new function for the plugin, where the plugin automatically adds that config, whenever _Initialization_ is enabled? :-D

If not, how about changing the docs to suggest the scheme you mention in #341 -- whether or not there will be repos managed outside of Redmine, still create a separate `.conf` for Redmine and just include that in `gitolite.conf`?

What do you think?

**Comment by n-rodriguez** [comment]
> Since, to add the repo @all config, I have to do it by hand, do you think it's worth making this a new function for the plugin, where the plugin automatically adds that config, whenever Initialization is enabled? :-D

Added in commit https://github.com/jbox-web/redmine_git_hosting/commit/f294e1f5849aef7d55113f4f07cf238aca2d8b6c


> If not, how about changing the docs to suggest the scheme you mention in #341 -- whether or not there will be repos managed outside of Redmine, still create a separate .conf for Redmine and just include that in gitolite.conf? This way, we can add the repo @all config in the main gitolite.conf, without the risk of the plugin overwriting it.

Actually the @all repository shouldn't disappear after a repository update since modifications on Gitolite file are 'atomic' in that we modify only one repository at a time. 

Here the process :
1. load ```gitolite.conf``` file as a GitoliteAdmin object. (Repositories are loaded as GitoliteAdmin::Repository object and GitoliteAdmin has a reference for every one of them)
2. delete the updated repository from GitoliteAdmin references and regenerate it's configuration
3. add the new reference and rewrite the ```gitolite.conf``` file

So this is really weird that the @all repository disappears from ```gitolite.conf```.

**Comment by necramirez** [comment]
I'll wait for v1.0.3 to be released, before trying this.  Our setup is working smoothly right now, except we initialize new repos manually.  Wouldn't want to disturb the peace. :-p

Thanks!
