### ISSUE TITLE
[Feature Request] Send Archive as Email.

### ISSUE THREAD

**Issue by MrCheetah** [jbox-web/redmine_git_hosting#489]
Just a thought but how difficult would it be to add the ability to send an email to a client with a link to download a copy of the archive.

Basic rundown would be something like -

1) Select send to user and either type the name or grab it out of a dropdown for users associated with the project.

2) Click send which would basically create the zip but move it to a temporary directory and then use the native redmine email handler to send an automated email with that link.

Use Case -

We do Audio Video and Automation control programming where it's very common for the clients to want a copy of the code after the job is completed to have for records but they definitely aren't savvy enough to pull the repo. This would allow a rapid way to send source out to anyone who needs it.

Bonus points - Set a number of times the file can be downloaded and or expiration. Ability to send just a specific branch or revision.

**Comment by maxiv** [comment]
Must be ability send attachment, not link only.

**Comment by n-rodriguez** [comment]
> Must be ability send attachment, not link only.

Well, this is not recommanded as the attachment can be quite big (it depends on the repository size)

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
