### ISSUE TITLE
Pushing to redmine as a mirror fails

### ISSUE THREAD

**Issue by wherget** [jbox-web/redmine_git_hosting#579]
Hi!
I'm trying to mirror to `redmine_git_hosting` using
```
$ git push redmine +refs/remotes/origin/*:refs/heads/*
Counting objects: 121, done.
Delta compression using up to 16 threads.
Compressing objects: 100% (121/121), done.
Writing objects: 100% (121/121), 12.31 KiB | 0 bytes/s, done.
Total 121 (delta 94), reused 0 (delta 0)
remote: FATAL: + refs/heads/feature/somebranch myrepo redmine_myuser_1 DENIED by fallthru
remote: error: hook declined to update refs/heads/feature/somebranch
To git@redmine:myrepo.git
 ! [remote rejected] origin/feature/somebranch -> feature/somebranch (hook declined)
```
It looks like I'm missing the + permission, any idea what might be missing? Do I need to configure a specific permission in the respective redmine role?

**Comment by l337r007** [comment]
After reading a bit of code I found out a solution myself. To get the `+` in gitolite, you need the `Manage Repository` permission in your role.
Alternatively (and this is the way I chose to do it now), configure a deployment key with the `RW+` permission. I only really found out how deployment keys work after reading the permission code. I think the feature could be documented better, because it seems really useful (giving specific keys elevated permissions).

**Comment by n-rodriguez** [comment]
> After reading a bit of code I found out a solution myself

Hope this was not too ugly :)

**Comment by l337r007** [comment]
To be honest, there were a couple too many levels of indirection for my liking. ;) My journey started out from the rake `regenerate_ssh_keys` task and I finally found `Gitolitable::Users` (via `GitoliteAccessor`, `GitoliteWrappers::Base`, `GitoliteHandlers::Repositories::Base`, `Gitolitable::Permissions` and `PermissionsBuilder:: Standard`).
If I were to name something actionable in this issue, I think http://redmine-git-hosting.io/features/ could be less self-referential under "Deployment Credentials". Maybe something along the lines of
> Grant access to repositories for specific keys, no redmine user necessary. Great for service integrations such as build services or repository mirrors!

**Comment by n-rodriguez** [comment]
Doc updated. Thank you!
