### ISSUE TITLE
Configuring the automatic display of README files

### ISSUE THREAD

**Issue by jjongbloets** [jbox-web/redmine_git_hosting#602]
In my repositories I have multiple README files, I have a README.Rmd (rmarkdown), a README.md (markdown), sometimes a README.html or just README.

From your code I gather that you find all README files matching `README.*` and use the first file (in my case README.Rmd). I would like to redmine to show the README.md instead.

Is it possible to implement a priority list where users can configure the order in which redmine should try to load the different README files. Or add a input field in the repository settings menu, such that users are able to select which file has to be shown as README file per project.

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
