### ISSUE TITLE
Inconsistencies when project renamed with "project_alias_2" (Redmine plugin)

### ISSUE THREAD

**Issue by mbideau** [jbox-web/redmine_git_hosting#633]
When using the plugin _project_alias_2_ (basically just a project renaming), the _git_hosting_ plugin is confused : 

In the repository page :
* The repo is displayed like existing but empty, instead of existing with the old name and not empty or not existing with the new name

In the configuration page :
* The URL of the repo displayed is with the new name
* Icon warning on 'Le dépôt existe dans Gitolite'
* The URL following 'Parcourir les sources' is even more broken : displays the old name but point to the new name

**Comment by n-rodriguez** [comment]
Hi! This happens because *project_alias_2* is doing a raw sql query to rename the project. (https://github.com/paginagmbh/redmine_project_alias_2/blob/master/app/models/project_alias.rb)

Thus it doesn't call any Rails hooks or callbacks I could hook on. 
Renaming a project with repositories is not a basic operation as it will move the repo hierarchy to match the project one.

If you don't want this behavior you can switch to the flat repo organization.

**Comment by mbideau** [comment]
Sorry for the LONG delay, and thanks for your feedback.

I was already with the flat repo organization (as you suggested).

Although you can't hook up on the rename operation, maybe some UI inconsistencies can be fixed by always looking at the same source of data regarding the project name. Whether its the old name or the new one, all the UI in git_hosting_plugin UI should display the same info, I suppose.

I'm sorry I can't help much.

I've not thanked you last time, but you've made a great peace of software that help many people I think, so thank you and keep up the good work ;-)

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
