### ISSUE TITLE
CSS Overreach

### ISSUE THREAD

**Issue by sdfg2** [jbox-web/redmine_git_hosting#644]
The CSS included as part of the bootstrap isn't selective enough to only apply to the specific sections of the website where it's needed.  For example: all entries in the project settings page are altered by the inclusion of the stylesheet which it seems should only apply to the repositories part of the project settings.

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
