### ISSUE TITLE
Bad line length character on clone

### ISSUE THREAD

**Issue by sdfg2** [jbox-web/redmine_git_hosting#652]
I created a brand new project in Redmine to test this plugin. I have it set to create the readme automagically.  Whenever I try and clone it (I've tried on the command line and in eclipse) I get the following.

`Cloning into 'scratch3'...
fatal: protocol error: bad line length character: 14d
fatal: The remote end hung up unexpectedly`

Any pointers?

**Comment by sdfg2** [comment]
Anyone?  I really need a hand with this, I've tried looking around bashrc files and so on, but all the instructions for troubleshooting this expect raw git, without an intermediary like this plugin.

**Comment by Reborns** [comment]
Not shure about Eclipse but command line works just fine , also on Windows Pycharm and TortoiseGit works as expected .. Cloning and pushing

**Comment by Reborns** [comment]
**adfg2**  Waht is  login shell  for you git user ??? try to set it to /bin/bash

**Comment by sdfg2** [comment]
It is /bin/bash.

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
