### ISSUE TITLE
new release with clean Gemfile?

### ISSUE THREAD

**Issue by costela** [jbox-web/redmine_git_hosting#670]
Hi,

Would it be possible to release a new version or maybe backport the newer cleaner Gemfile to the 1.2.x branch?
A bit of context: we're provisioning redmine + plugins automatically with puppet, which breaks because of the duplicate declaration of `redcarpet` in redmine's Gemfile and the plugin's Gemfile (during `bundle install`). This requires either manual intervention or some plugin-specific hacks around our provisioning code.
Of course we could peg our provisioning to a specific commit of `redmine_git_hosting` that includes the fix, but we couldn't really tell if you're still in the middle of some big refactoring, or if `master`'s code is supposed to be considered stable.

Thanks for considering! :)

**Comment by n-rodriguez** [comment]
Hi! I perfectly understand your requirements (that's why https://github.com/jbox-web/redmine_git_hosting/commit/60716acca5aea0eda52c8bb1a95e42d38eb49294 and https://github.com/jbox-web/redmine_git_hosting/commit/a111ac8cc552f8a4f844b43263dd1bb54893bee6).
The thing is that for the gems versions management there's nothing I can do as it strongly depends on the Redmine version :

```
nicolas@desktop:~/PROJECTS/REDMINE_DEV$ grep rdoc redmine*/Gemfile
redmine-2.5.2/Gemfile:  gem "rdoc", ">= 2.4.2"
redmine-2.6.2/Gemfile:  gem "rdoc", ">= 2.4.2"
redmine-2.6.4/Gemfile:  gem "rdoc", ">= 2.4.2"
redmine-2.6/Gemfile:  gem "rdoc", ">= 2.4.2"
redmine-3.0.0/Gemfile:  gem "rdoc", ">= 2.4.2"
redmine-3.0.3/Gemfile:  gem "rdoc", ">= 2.4.2"
redmine-3.1.0/Gemfile:  gem "rdoc", ">= 2.4.2"
redmine-3.1.1/Gemfile:  gem "rdoc", ">= 2.4.2"
redmine-3.2.0/Gemfile:  gem "rdoc", ">= 2.4.2"
redmine-3.3.0/Gemfile:  gem "rdoc", ">= 2.4.2"
redmine-3.3.2/Gemfile:  gem "rdoc", "~> 4.3"
redmine-3.3.3/Gemfile:  gem "rdoc", "~> 4.3"
```

```
nicolas@desktop:~/PROJECTS/REDMINE_DEV$ grep redcarpet redmine*/Gemfile
redmine-2.5.2/Gemfile:    # TODO: upgrade to redcarpet 3.x when ruby1.8 support is dropped
redmine-2.5.2/Gemfile:    gem "redcarpet", "~> 2.3.0"
redmine-2.6.2/Gemfile:    # TODO: upgrade to redcarpet 3.x when ruby1.8 support is dropped
redmine-2.6.2/Gemfile:    gem "redcarpet", "~> 2.3.0"
redmine-2.6.4/Gemfile:    # TODO: upgrade to redcarpet 3.x when ruby1.8 support is dropped
redmine-2.6.4/Gemfile:    gem "redcarpet", "~> 2.3.0"
redmine-2.6/Gemfile:    # TODO: upgrade to redcarpet 3.x when ruby1.8 support is dropped
redmine-2.6/Gemfile:    gem "redcarpet", "~> 2.3.0"
redmine-3.0.0/Gemfile:    gem "redcarpet", "~> 3.1.2"
redmine-3.0.3/Gemfile:    gem "redcarpet", "~> 3.1.2"
redmine-3.1.0/Gemfile:    gem "redcarpet", "~> 3.1.2"
redmine-3.1.1/Gemfile:    gem "redcarpet", "~> 3.3.2"
redmine-3.2.0/Gemfile:    gem "redcarpet", "~> 3.3.2"
redmine-3.3.0/Gemfile:    gem "redcarpet", "~> 3.3.2"
redmine-3.3.2/Gemfile:    gem "redcarpet", "~> 3.3.2"
redmine-3.3.3/Gemfile:    gem "redcarpet", "~> 3.3.2"
```

Gem installation happens in a very early stage and at this point I cannot know the Redmine version installed without some magical and ugly tricks to guess the Redmine root dir.

**Comment by n-rodriguez** [comment]
By the way : there is a new release : https://github.com/jbox-web/redmine_git_hosting/releases

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
