### ISSUE TITLE
[FEATURE] Hierachical depth limit

### ISSUE THREAD

**Issue by pale3** [jbox-web/redmine_git_hosting#678]
## E.g  checkout url:
`https://redmine/project/subproject/subsubproject/foo.git`

## Stored on disk:
<pre>
repositories/
└── project/
    └── subproject/
        └── subsubproject/
            └── foo.git
</pre>

Would it be possible in hierarchical style to invent depth. So for ^above when limiting it to "Depth 1" will store foo.git within parent called "subsubproject".

## checkout url:
 `https://redmine/subsubproject/foo.git`
<pre>
repositories/
└── subsubproject/
       └── foo.git
</pre>

@n-rodriguez , please comment

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
