### ISSUE TITLE
Enabling protected branches disables the deploy keys

### ISSUE THREAD

**Issue by mnencia** [jbox-web/redmine_git_hosting#683]
The current implementation of protected branches totally disables the deploy keys feature, without any warning.

I think that it's not the correct behaviour, but in case it's the desired one, please document it somewhere.

**Comment by gituser** [comment]
hi, i've got the same problem.

any chance you could fix this?
either add an option to allow/disallow deployment keys (already added ones) access all branches or add an option to select which deployment keys could access certain protected branch.

thank you.

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.

**Comment by mnencia** [comment]
This is still relevant even for development code. Please reopen.
