### ISSUE TITLE
NoMethodError (undefined method `plugin_redmine_git_hosting'

### ISSUE THREAD

**Issue by mtolava** [jbox-web/redmine_git_hosting#686]
Hello
I can not use the plugin, when I try to enter to the settings show me this error:
``
`NoMethodError (undefined method plugin_redmine_git_hosting for #<Class:0x000000041cf828>):`

Im using:
 Environment:
  Redmine version                2.6.10.stable.15413
  Ruby version                   2.2.4-p230 (2015-12-16) [x86_64-linux]
  Rails version                  3.2.22.2
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.3
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  redmine_bootstrap_kit          0.2.5
  redmine_custom_help_url        0.0.2
  redmine_git_hosting            1.2.3
  redmine_knowledgebase          3.0.7
  redmine_monitoring_controlling 0.1.1
  timelog_timer                  2.0.0

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
