### ISSUE TITLE
git-daemon-export-ok not installed in myproject.git

### ISSUE THREAD

**Issue by schrein** [jbox-web/redmine_git_hosting#689]
Hello,

I'm trying to set up a public git repository for read only access.

I have configured git-daemon, and check the .gitolite.rc for ENABLE => [ 'daemon' ] parameter. 

I have set these parameters in redmine:

- myproject > settings > information > **public**
- myproject > settings > repository > **enable git daemon** , **make repository public**, "smart http mode deactivated"

My project properly show git URL for RO access in Redmine interface but I can not git clone as an anonymous user. 

Finally, If I manually add git-daemon-export-ok file inside myproject.git, I can clone the repository as an anonymous user. But the git-daemon-export-ok file is deleted after any Redmine project configuration update 

My current environment:

Environment:
  Redmine version                3.2.1.stable
  Ruby version                   2.3.1-p112 (2016-04-26) [x86_64-linux-gnu]
  Rails version                  4.2.6
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.3
  Git                            2.7.4
  Filesystem                     
  Xitolite                       2.7.4
Redmine plugins:
  redmine_bootstrap_kit          0.2.5
  redmine_git_hosting            1.2.2

**Comment by heing** [comment]
I found out that project must be in public and you need to allow anonymous role to view changesets.

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
