### ISSUE TITLE
NameError: uninitialized constant Faker::Base

### ISSUE THREAD

**Issue by m-ramizraja** [jbox-web/redmine_git_hosting#704]
I followed steps mentioned on this page,
http://redmine-git-hosting.io/get_started

When I run following command, 

- bundle exec rake redmine:plugins:migrate RAILS_ENV=production NAME=redmine_git_hosting

I got this error,

NameError: uninitialized constant Faker::Base
/Users/ramizraja/projects/vnc/redmine-testing/plugins/redmine_git_hosting/lib/core_ext/faker/git.rb:2:in `<module:Faker>'
/Users/ramizraja/projects/vnc/redmine-testing/plugins/redmine_git_hosting/lib/core_ext/faker/git.rb:1:in `<top (required)>'
/Users/ramizraja/projects/vnc/redmine-testing/plugins/redmine_git_hosting/lib/redmine_git_hosting.rb:91:in `block in <top (required)>'
/Users/ramizraja/.rvm/gems/ruby-2.3.0@vredmine/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:446:in `instance_exec'
/Users/ramizraja/.rvm/gems/ruby-2.3.0@vredmine/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:446:in `block in make_lambda'

How can I fix this?

_**Redmine version: 3.2.1**_

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
