### ISSUE TITLE
Push tags with protected branches

### ISSUE THREAD

**Issue by drewlsvern** [jbox-web/redmine_git_hosting#706]
How do I go about setting permissions to update tags when I have protected branches enabled?

Here is the error I receive.
```
remote: FATAL: W refs/tags/test-tag repositories/redmine/rms-ctp-tessitura redmine_user_name_6 DENIED by fallthru   
remote: error: hook declined to update refs/tags/test-tag  
```

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
