### ISSUE TITLE
Multiple concurrent repo-changes by redmine result in rollback of oldest concurrent changes

### ISSUE THREAD

**Issue by Snicksie** [jbox-web/redmine_git_hosting#710]
I run redmine_git_hosting in a redmine instance with a >50 amount of active accounts that can create new repositories and/or change access rights to repositories. Changing access rights is an operation that takes a fairly long amount of time (~1-2minutes?). If two people are logged in at the same time, and one person first changes access rights, and within the time period of this 1-2 minutes another person creates a new repository (or also changes access rights), the changes made by the first person are undone in gitolite.conf (in gitolite-admin.git/conf/gitolite.conf). Lets assume before the two changes, the file has version a. Person 1 changes access rights to repository x and changes the file to version b. Person 2 adds a repository y, in the 1-2 minute time window. Redmine uses version a (not version b!) of the file to add this repository. This means the access rights for repository x will be back to those as in version a.

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
