### ISSUE TITLE
Mostly cosmetic.

### ISSUE THREAD

**Issue by dvarvell** [jbox-web/redmine_git_hosting#711]
1) Why does my repository listing only have two columns (Name, Size)
![repo_listing](https://user-images.githubusercontent.com/37552966/37614449-0176c8f6-2b68-11e8-91e9-4f17d12b4a9d.jpg)

2) Why are the access links docked above the listing instead of using buttons on the right.
![repo_listing_2](https://user-images.githubusercontent.com/37552966/37614829-f5fee3cc-2b68-11e8-84ec-a02443b3d8ce.jpg)

3) What does "GO" mean in the access links. How do I disable it. I only want SSH and HTTPS.

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
