### ISSUE TITLE
Docker Setup

### ISSUE THREAD

**Issue by pmayer** [jbox-web/redmine_git_hosting#718]
According to the FAQ it's possible to have Gitolite and Redmine on different servers – so I tried a docker setup with 2 containers (Gitolite and Redmine) and a shared volume, but can't get it to work. Does anyone have a working setup and would be so nice to share it?

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
