### ISSUE TITLE
Exception ScmCommandAborted is not thrown if the cache is disabled and the Git command return a non-zero exit code

### ISSUE THREAD

**Issue by xel1045** [jbox-web/redmine_git_hosting#722]
The behaviour change between `ShellRedirector.execute` and `AbstractAdapter.shellout`:

```
if !git_cache_id.nil? && git_cache_enabled? && !bypass_cache
  RedmineGitHosting::ShellRedirector.execute(cmd_str, git_cache_id, options, &block)
else
  Redmine::Scm::Adapters::AbstractAdapter.shellout(cmd_str, options, &block)
end
```

The method `ShellRedirector.execute` will check for the exit code, but `AbstractAdapter.shellout` not. It's then impossible to extend the adapter and use the Git status code.

Redmine's Git adapter also check the status code that way:

```
        def git_cmd(args, options = {}, &block)
          # ...
          ret = shellout(
                   self.class.sq_bin + ' ' + full_args.map { |e| shell_quote e.to_s }.join(' '),
                   options,
                   &block
                   )
          if $? && $?.exitstatus != 0
            raise ScmCommandAborted, "git exited with non-zero status: #{$?.exitstatus}"
          end
          ret
        end
```

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
