### ISSUE TITLE
Redmine 3.4.6 + redmine_git_hosting 1.2.3 + Git 2.17

### ISSUE THREAD

**Issue by Idleworks** [jbox-web/redmine_git_hosting#723]
I recently installed latest redmine 3.4.6 on a Bitnami Stack with redmine_git_hosting 1.2.3.
Config Test says everything is 'ok'.

Now, when adding new git repositories in redmine, gitolite doesn't create them in my configured directory.

redmine_git_hosting.log shows
<pre>[ERROR] Git exited with non-zero status : 128 : 'sudo' '-n' '-u' 'git' '-i' 'git' '--git-dir' 'repositories/git-test/test.git' '-c' 'core.quotepath=false' '-c' 'log.decorate=no' 'branch' '--verbose' '--no-abbrev'</pre>

I already patched files mentioned in #720 but that had no effect.

For now the only possible way to me is downgrading git to version 2.11 - that in fact is a huge act in a bitnami stack. 
Is this a known compatibility issue with redmine_git_hosting and git 2.17?

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
