### ISSUE TITLE
how to re-init binary files

### ISSUE THREAD

**Issue by sapeyes** [jbox-web/redmine_git_hosting#731]
Hi,

Yesterday,  I found my redmine is not working.

I tried to reinitialize RVM and ruby (2.14) environment. 

Finally this redmine works well but gitolite binary isn't there. 

Also I updated gitolite to 1.2.3 from 1.1.1 just to be the latest mode

![image](https://user-images.githubusercontent.com/960277/56543315-16a1e600-65ac-11e9-9b7b-88c242b7fb55.png)

What should I do ?

**Comment by sapeyes** [comment]
When I run gitolite in this console (git account) it shows an error message.

![image](https://user-images.githubusercontent.com/960277/59248061-47250880-8c5c-11e9-86c9-13e7f1bf008b.png)


I installed all things by following this site.
*  https://www.redmine.org/projects/redmine/wiki/HowTo_Install_Redmine_30x_on_Ubuntu_1404_with_Apache2_Phusion_Passenger_MySQL_Subversion_and_Git_(Gitolite)#Redmine-Git-Hosting-Plugin

It had been working well for more than two years.
Recently I tested new plugin and I met some errors. 
Therefore I reinstalled rvm, ruby and bundler and its related.
My redmine is now working well but only the gitolite binaries directory is not working.

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
